---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  ports:
  - port: 8080
    name: restfulapi
  - port: 2181
    name: client
  - port: 2888
    name: server
  - port: 3888
    name: election
  clusterIP: None
  selector:
    app: zookeeper
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-zookeeper
data:
  jvm.heap: "1G"
  tick: "2000"
  init: "10"
  sync: "5"
  client.cnxns: "60"
  purge.interval: "0"
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: pdb-zookeeper
spec:
  selector:
    matchLabels:
      app: zookeeper
  minAvailable: 2
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
spec:
  serviceName: zookeeper 
  replicas: 3
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values: 
                    - zookeeper
              topologyKey: "kubernetes.io/hostname"
      imagePullSecrets:
      - name: eju-docker-hub
      containers:
      - name: fangzookeeper
        imagePullPolicy: Always
        image: oyymmw/zookeeper:3.5.5
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
        ports:
        - containerPort: 8080
          name: restfulapi
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election
        env:
        - name : ZOO_REPLICAS
          value: "3"
        - name : ZOO_HEAP_SIZE
          valueFrom:
            configMapKeyRef:
                name: cm-zookeeper
                key: jvm.heap
        - name : ZOO_TICK_TIME
          valueFrom:
            configMapKeyRef:
                name: cm-zookeeper
                key: tick
        - name : ZOO_INIT_LIMIT
          valueFrom:
            configMapKeyRef:
                name: cm-zookeeper
                key: init
        - name : ZOO_SYNC_LIMIT
          valueFrom:
            configMapKeyRef:
                name: cm-zookeeper
                key: tick
        - name : ZOO_MAX_CLIENT_CNXNS
          valueFrom:
            configMapKeyRef:
                name: cm-zookeeper
                key: client.cnxns
        - name: ZOO_PURGE_INTERVAL
          valueFrom:
            configMapKeyRef:
                name: cm-zookeeper
                key: purge.interval
        - name: ZOO_CLIENT_PORT
          value: "2181"
        - name: ZOO_SERVER_PORT
          value: "2888"
        - name: ZOO_ELECTION_PORT
          value: "3888"
        readinessProbe:
          exec:
            command:
            - "zkOk.sh"
          initialDelaySeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
            - "zkOk.sh"
          initialDelaySeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - name: datadir
          mountPath: /var/lib/zookeeper
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "storageclases_name"
      resources:
        requests:
          storage: 1Gi
